config/routes.rb
Rails.application.routes.draw do


  resources :contacts do
    collection do
        post :import
    end
  end

  get '/create_msg' => 'messages#text_form'

  post '/send_my_text' => 'messages#send_my_text'
  # post '/reply' => 'messages#reply'
  # Create Endpoint in Twilio Dashboard "www.schwell.com/messages/reply"

  root 'static_pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    require 'csv'

    def self.import(imported_file)
        input_path = imported_file.path
        CSV.foreach(input_path, headers: true) do |row|
            name = row[0]
            number = row[1]

            next if !number

            valid_number = number.scan(/\d+/).join
            valid_number[0] == "1" ? valid_number[0] = '' : valid_number
            valid_number unless valid_number.length != 10

            if name && valid_number
                Contact.create(name: name, phone_num: valid_number)
            end
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    @contact = Contact.import(params[:file])
    redirect_to root_url, notice: "Contacts Imported Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone_num)
    end
  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    skip_before_filter :verify_authenticity_token
    require 'twilio-ruby'


    def text_form

    end

    def send_my_text
        message_body = params["body"]
        boot_twilio

        # sms = @client.messages.create(
        #     from: Rails.application.secrets.twilio_number,
        #     to: '8475088751',
        #     body: message_body
        #     )

        @contacts = Contact.all

        @successful_msg = 0
        @contacts.each do |contact|
            sms = @client.messages.create(
                from: Rails.application.secrets.twilio_number,
                to: contact.phone_num,
                body: message_body
                )
            @successful_msg += 1
            sleep(5)
        end

        redirect_to root_path, :notice => "We sent #{@successful_msg} messages out of #{@contacts.count} contacts successfully"

    end

    # def reply
    #     message_body = params["Body"] # Responders messages
    #     from_number  = params["From"] # Responders number
    #     boot_twilio

    #     sms = @client.messages.create(
    #         from: Rails.application.secrets.twilio_number,
    #         to: from_number,
    #         body: "You responded with #{message_body}"
    #         )
    #     redirect_to(:back)
    # end

    private

    def boot_twilio
        account_sid = Rails.application.secrets.twilio_sid
        auth_token = Rails.application.secrets.twilio_token
        @client = Twilio::REST::Client.new account_sid, auth_token
    end
end

app/controllers/sms_deliveries_controller.rb
class SmsDeliveriesController < ApplicationController
    require 'twilio-ruby'

    def create_message

    end

    def send_text
        message_body = params["body"]
        boot_twilio

        sms = @client.messages.create(
            from: '18472326161',
            to: '8475088751',
            body: message_body
            )

        # contacts = Contact.all

        # contacts.each do |contact|
        #     sms = @client.messages.create(
        #         from: # add your twilio number here
        #         to: contact.phone_num,
        #         body: message_body
        #         )
        # end

        # twilio_sid = Rails.application.secrets.twilio_sid
        # twilio_token = Rails.application.secrets.twilio_token

        # @client = Twilio::REST::Client.new(twilio_sid, twilio_token)

        # sms = @client.messages.create(
        #     :body => "Here is a test did it work?",
        #     :to => "8475088751",
        #     :from => "+18475088751")

        redirect_to root_path, :notice => "We sent the text successfully"

    end

    private

    def boot_twilio
        account_sid = Rails.application.secrets.twilio_sid
        auth_token = Rails.application.secrets.twilio_token
        @client = Twilio::REST::Client.new account_sid, auth_token
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sms_delivery_helper.rb
module SmsDeliveryHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_num %><br>
    <%= f.text_field :phone_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-md-6">
        <%= form_tag import_contacts_path, class: "form-group", multipart: true do %>
        <%= file_field_tag :file, class: "form-control" %>
        <%= submit_tag "Import", class: "form-control btn-primary" %>
        <% end %>
    </div>
    <div class="col-md-6">
        <p><%= link_to 'New Contact', new_contact_path %></p>
        <p><%= link_to "Create a message", create_msg_url %></p>
    </div>
</div>


<div class="contacts">
    <div class="row">
        <h1>Contacts</h1>
    </div>

    <% @contacts.each do |contact| %>
    <div class="col-md-6">
        <div class="nametag">
            <p><small>Name:</small> <%= contact.name %></p>
            <p><small>Number:</small> <%= contact.phone_num %></p>
            <%= link_to "Delete", contact, method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
        <br>
    </div>
    <% end %>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone num:</strong>
  <%= @contact.phone_num %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealEstateContactMessanger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<%= yield %>
</div>

</body>
</html>

app/views/messages/message_form.html.erb
<h1>Create your message here</h1>
<small>This will send to your whole contact list</small>

<%= form_tag('/send_my_text') do %>
    <div><%= text_area_tag 'body' %></div>
    <div><%= submit_tag 'Send Message' %></div>
<% end %>

app/views/messages/msg_form.html.erb
<h1>Create your message here</h1>
<small>This will send to your whole contact list</small>

<%= form_tag('/send_my_text') do %>
    <div><%= text_area_tag 'body' %></div>
    <div><%= submit_tag 'Send Message' %></div>
<% end %>

app/views/messages/text_form.html.erb
<h1>Create your message here</h1>
<small>This will send to your whole contact list</small>

<%= form_tag('/send_my_text') do %>
    <div><%= text_area_tag 'body' %></div>
    <div><%= submit_tag 'Send Message' %></div>
<% end %>

app/views/static_pages/home.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <p><%= link_to "All contacts", contacts_url %></p>
    <p><%= link_to "Create a message", create_msg_url %></p>
</div>
<table class="table">
    <tr>
        <th>CONTACTS</th>
        <th>TEXTS SENT OUT</th>
    </tr>
    <tr>
        <td><%= Contact.count %></td>
        <td></td>
    </tr>
</table>